### ISSUE TITLE
Ubuntu Studio - Provisioning malfunction

### ISSUE THREAD

**Issue by eeickmeyer** [canonical/ubuntu-desktop-provision#421]
Installed provisioning for Ubuntu Studio, and despite having the attached `whitelist.yaml` file in `/usr/share/ubuntu-provision`, I get the following:

![VirtualBox_ISOTest_13_02_2024_18_20_32](https://github.com/canonical/ubuntu-desktop-provision/assets/7434781/b07b6855-222b-4474-8d02-e390086e72af)

As you can see, the branding (Kubuntu) is wrong.

Here's the terminal output:

```
(ubuntu_bootstrap:4458): Gdk-CRITICAL **: 02:33:01.708: gdk_window_get_state: assertion 'GDK_IS_WINDOW (window)' failed
flutter: INFO ubuntu_bootstrap: Logging to /var/log/installer/ubuntu_bootstrap.log
flutter: WARNING subiquity_server: Unable to find the subiquity_client package. Falling back to the current working dir: /usr/share/ubuntu-provision
flutter: INFO subiquity_server: Waiting server up to 90 seconds
flutter: INFO subiquity_server: ApplicationState.WAITING
flutter: INFO subiquity_client: Opening socket to Endpoint(/run/subiquity/socket )
flutter: DEBUG desktop: Disabling automounting
flutter: DEBUG subiquity_client: POST http://localhost/meta/client_variant?variant=%22desktop%22
flutter: DEBUG subiquity_client: GET http://localhost/refresh?wait=true
flutter: DEBUG telemetry: Writing report to /var/log/installer/telemetry
flutter: DEBUG subiquity_client: ==> setVariant(Variant.DESKTOP) null
flutter: DEBUG subiquity_client: ==> checkRefresh() {"availability": "UNAVAILABLE", "current_snap_version": "0+git.15cde5fb", "new_snap_version": ""}
flutter: DEBUG refresh: RefreshState.status(status: RefreshStatus(availability: RefreshCheckState.UNAVAILABLE, currentSnapVersion: 0+git.15cde5fb, newSnapVersion: ))
flutter: INFO subiquity_status: null => ApplicationStatus(state: ApplicationState.WAITING, confirmingTty: , error: null, cloudInitOk: true, interactive: true, echoSyslogId: subiquity_echo.2980, logSyslogId: subiquity_log.2980, eventSyslogId: subiquity_event.2980)
flutter: DEBUG subiquity_client: POST http://localhost/meta/mark_configured?endpoint_names=%5B%22mirror%22%2C%22proxy%22%2C%22ssh%22%2C%22snaplist%22%2C%22ubuntu_pro%22%5D
flutter: DEBUG subiquity_client: ==> markConfigured([mirror, proxy, ssh, snaplist, ubuntu_pro]) null
flutter: ERROR desktop: Failed to set automount to DBusBoolean(false)
        PathNotFoundException: PathNotFoundException: Cannot open file, path = '/etc/dconf/db/site' (OS Error: No such file or directory, errno = 2)
flutter: ERROR desktop: Failed to set automount-open to DBusBoolean(false)
        PathNotFoundException: PathNotFoundException: Cannot open file, path = '/etc/dconf/db/site' (OS Error: No such file or directory, errno = 2)
flutter: ERROR desktop: Failed to set autorun-never to DBusBoolean(true)
        PathNotFoundException: PathNotFoundException: Cannot open file, path = '/etc/dconf/db/site' (OS Error: No such file or directory, errno = 2)
flutter: ERROR desktop: Failed to set show-volumes to DBusBoolean(false)
        GSettingsSchemaNotInstalledException: GSettings schema org.gnome.shell.extensions.ding not installed
flutter: ERROR desktop: Failed to set show-network-volumes to DBusBoolean(false)
        GSettingsSchemaNotInstalledException: GSettings schema org.gnome.shell.extensions.ding not installed
flutter: DEBUG desktop: Disabling screen blanking
flutter: ERROR desktop: Failed to set idle-delay to DBusUint32(0)
        PathNotFoundException: PathNotFoundException: Cannot open file, path = '/etc/dconf/db/site' (OS Error: No such file or directory, errno = 2)
flutter: DEBUG desktop: Disabling screensaver
flutter: ERROR desktop: Failed to set idle-activation-enabled to DBusBoolean(false)
        PathNotFoundException: PathNotFoundException: Cannot open file, path = '/etc/dconf/db/site' (OS Error: No such file or directory, errno = 2)
flutter: DEBUG desktop: Inhibiting Gnome session
flutter: ERROR desktop: Failed to inhibit Gnome Session
        DBusServiceUnknownException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files
flutter: INFO subiquity_status: null => ApplicationStatus(state: ApplicationState.WAITING, confirmingTty: , error: null, cloudInitOk: true, interactive: true, echoSyslogId: subiquity_echo.2980, logSyslogId: subiquity_log.2980, eventSyslogId: subiquity_event.2980)
flutter: INFO subiquity_status: null => ApplicationStatus(state: ApplicationState.WAITING, confirmingTty: , error: null, cloudInitOk: true, interactive: true, echoSyslogId: subiquity_echo.2980, logSyslogId: subiquity_log.2980, eventSyslogId: subiquity_event.2980)
flutter: DEBUG subiquity_client: GET http://localhost/meta/interactive_sections
flutter: DEBUG subiquity_client: ==> getInteractiveSections() null
flutter: INFO locale: Loaded 75 languages
flutter: DEBUG subiquity_client: GET http://localhost/locale
flutter: DEBUG subiquity_client: ==> locale() "C.UTF-8"
flutter: INFO locale: Selected en_US as UI language
flutter: ERROR ubuntu_bootstrap: Unhandled exception
        ProcessException: ProcessException: No such file or directory
  Command: canberra-gtk-play --id=system-ready
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:402)
#1      Process.start (dart:io-patch/process_patch.dart:38)
#2      _runNonInteractiveProcess (dart:io-patch/process_patch.dart:579)
#3      Process.run (dart:io-patch/process_patch.dart:49)
#4      SoundService.play (package:ubuntu_provision/src/services/sound_service.dart:5)
#5      LocaleModel.playWelcomeSound (package:ubuntu_provision/src/locale/locale_model.dart:83)
#6      LocalePage.load.<anonymous closure> (package:ubuntu_provision/src/locale/locale_page.dart:13)
#7      _rootRunUnary (dart:async/zone.dart:1407)
<asynchronous suspension>
#8      DefaultEquality.isValidKey (package:collection/src/equality.dart:90)
<asynchronous suspension>
#9      _WizardBuilderState.initState.<anonymous closure>.<anonymous closure> (package:ubuntu_wizard/src/wizard_builder.dart:48)
<asynchronous suspension>
#10     WizardController._loadRoute (package:wizard_router/src/controller.dart:26)
<asynchronous suspension>
#11     WizardController.replace (package:wizard_router/src/controller.dart:154)
<asynchronous suspension>
```

Here's the whitelist.yaml:
```
# (Optional) Drives overall behaviour for specific provisioners.
#
# Options:
# - standard (default): the common provision flow for Ubuntu Desktop and Flavours
# - oem: enables the eula page and disables the user creation page during bootstrap
mode: standard

# (Optional) When set, the light and dark theme is inherited from ubuntu-flutter-plugins and the distro name is set.
#
# Options:
# - budgie
# - cinnamon
# - edubuntu
# - kubuntu
# - kylin
# - lubuntu
# - mate
# - studio
# - unity
# - xubuntu
flavour: studio

# (Optional) Sets the window's title (e.g. the text in alt|super + tab)
app-name: "Ubuntu Studio System Installer"

# (Optional) Overrides the theme's accent colors
#theme:
#  light:
#    accent-color: <color-hex-code> # i.e. #ff0011
#    elevated-button-color: <color-hex-code>
#    elevated-button-text-color: <color-hex-code>
#  dark:
#    accent-color: <color-hex-code> # i.e. #ff0011
#    elevated-button-color: <color-hex-code>
#    elevated-button-text-color: <color-hex-code>

# (Optional) Override a page's image asset.
# Images expected in /usr/share/desktop-provision/images/<image-name>
#
# Bootstrap pages:
# - locale: Select the interface language
# - accessibility: Allow user to configure GNOME accessibility options
# - rst: Identifies if the computer has Intel Rapid Storage Technology (rst) active
# - keyboard: Set keyboard layout
# - network: Connect to a network
# - refresh: Expose installer's auto-update mechanism
# - source: Install 3'rd party drivers and codecs
# - not-enough-disk-space: Notifies if there is insufficient disk space
# - secure-boot: Handles secure boot
# - storage: Select target disk and partition
# - identity: Create the first-user account (only displaed if mode = default)
# - confirm: A summary of the installation and confirmation button to start the install
#
# Init pages (for oem only)
# - identity: Create the first-user account 
# - ubuntu-pro: Enable Ubuntu Pro
# - privacy: Enable location services
# - timezone: Set the timezone
# - telemetry: Enable sending telemetry
pages:
  locale:
    image: "assets/mascot.png"
  accessibility:
#    image: "assets/images/accessibility.svg"
  try-or-install:
#    image: "assets/images/try-or-install.svg"
  rst:
#    image: "assets/images/rst.svg"
  keyboard:
#    image: "assets/images/keyboard.svg"
  network:
#    image: "assets/images/wifi.svg"
  refresh:
  source:
    image: "assets/images/mascot.svg"
  not-enough-disk-space:
  secure-boot:
  storage:
#    image: "assets/images/disk.svg"
  confirm:
```
